name: Build

on: 
  push:
    paths-ignore:
      - '**.md'   
  pull_request:
    branches:
      - master
    paths-ignore: 
      - '!**.md'  
  release:
    types:
      - released 

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout pygeoapi
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  main:
    needs: [flake8_py3]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: 3.8
          - python-version: 3.9
    env:
      PYGEOAPI_CONFIG: "$(pwd)/pygeoapi-config.yml"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PDM
      run: pipx install pdm
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Install and run PostgreSQL/PostGIS 📦
      uses: huaxk/postgis-action@v1
      with:
        postgresql password: ${{ secrets.DatabasePassword || 'postgres' }}
        postgresql db: 'test'
    - name: Install and run Elasticsearch 📦
      uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '7.6.1'
        host port: 9200
        container port: 9200
        host node port: 9300
        node port: 9300
        discovery type: 'single-node'
    - name: Install and run MongoDB
      uses: supercharge/mongodb-github-action@1.5.0
      with:
        mongodb-version: 4.4
    - name: Install and run SensorThingsAPI
      uses: cgs-earth/sensorthings-action@v0.0.2
    - name: Install sqlite and gpkg dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libsqlite3-mod-spatialite 
        version: 4.3.0a-6build1
    - name: Install requirements 📦
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND="noninteractive" sudo apt-get install -qy libgdal-dev
        pdm install --group :all
    - name: setup test data ⚙️
      run: |
        pdm run python tests/load_es_data.py tests/data/ne_110m_populated_places_simple.geojson geonameid
        pdm run python tests/load_es_data.py tests/cite/ogcapi-features/canada-hydat-daily-mean-02HC003.geojson IDENTIFIER
        pdm run python tests/load_mongo_data.py tests/data/ne_110m_populated_places_simple.geojson
        gunzip < tests/data/hotosm_bdi_waterways.sql.gz | psql postgresql://postgres:${{ secrets.DatabasePassword || 'postgres' }}@localhost:5432/test
    - name: run unit tests ⚙️
      env:
        POSTGRESQL_PASSWORD: ${{ secrets.DatabasePassword || 'postgres' }}
      run: |
        pdm run pytest tests/test_api.py
        pdm run pytest tests/test_config.py
        pdm run pytest tests/test_csv__formatter.py
        pdm run pytest tests/test_csv__provider.py
        pdm run pytest tests/test_elasticsearch__provider.py
        pdm run pytest tests/test_esri_provider.py
        pdm run pytest tests/test_filesystem_provider.py
        pdm run pytest tests/test_geojson_provider.py
        pdm run pytest tests/test_mongo_provider.py
        #pdm run pytest tests/test_ogr_csv_provider.py
        #pdm run pytest tests/test_ogr_esrijson_provider.py
        #pdm run pytest tests/test_ogr_gpkg_provider.py
        #pdm run pytest tests/test_ogr_shapefile_provider.py
        #pdm run pytest tests/test_ogr_sqlite_provider.py
        #pdm run pytest tests/test_ogr_wfs_provider.py
        pdm run pytest tests/test_openapi.py
        pdm run pytest tests/test_postgresql_provider.py
        pdm run pytest tests/test_rasterio_provider.py
        pdm run pytest tests/test_sensorthings_provider.py
        pdm run pytest tests/test_socrata_provider.py
        pdm run pytest tests/test_sqlite_geopackage_provider.py
        pdm run pytest tests/test_tinydb_catalogue_provider.py
        pdm run pytest tests/test_util.py
        pdm run pytest tests/test_xarray_netcdf_provider.py
        pdm run pytest tests/test_xarray_zarr_provider.py
    - name: build docs 🏗️
      run: cd docs && make html
    - name: failed tests 🚩
      if: ${{ failure() }}
      run: |
        pdm list --graph
